# Generated by Django 5.0.2 on 2024-03-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=10)),
                ('lname', models.CharField(max_length=10)),
                ('email', models.CharField(default='0', max_length=10)),
                ('password', models.CharField(default='0', max_length=10)),
            ],
        ),
    ]
