# Generated by Django 5.0.2 on 2024-03-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='calculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num1', models.CharField(max_length=10)),
                ('num2', models.CharField(max_length=10)),
                ('op', models.CharField(max_length=10)),
                ('result', models.CharField(max_length=10)),
            ],
        ),
    ]
