# Generated by Django 5.0.2 on 2024-03-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0002_calculator'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('photo', models.FileField(default='0', upload_to='photo')),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(default='0', max_length=30),
        ),
    ]
