# Generated by Django 5.0.2 on 2024-03-13 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0003_employee_alter_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(default='0', upload_to='media/photo'),
        ),
    ]
