# Generated by Django 5.0.2 on 2024-03-13 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0004_alter_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.FileField(default='0', upload_to='media/photo'),
        ),
    ]
