# Generated by Django 5.0.2 on 2024-03-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerForm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcustomer',
            name='adress',
            field=models.TextField(max_length=100),
        ),
    ]
